export const mockData = [
  {
    companyName: "Smith & Sons Carpentry",
    tradespersonName: "John Smith",
    primaryIndustry: "Carpenters & Joiners",
    fullAddress: "123 Oak Street, London",
    postcode: "SW1A 1AA",
    websiteUrl: "https://smithcarpentry.co.uk",
    phoneNumber: "020 7123 4567",
    emailAddress: "john@smithcarpentry.co.uk",
    sourceUrl: "https://maps.google.com/",
    dateOfScraping: "2025-01-15"
  },
  {
    companyName: "London Builders Ltd",
    tradespersonName: "Sarah Johnson",
    primaryIndustry: "General Builders",
    fullAddress: "45 Victoria Road, London",
    postcode: "SW1A 2BB",
    websiteUrl: "https://londonbuilders.com",
    phoneNumber: "020 7234 5678",
    emailAddress: "sarah@londonbuilders.com",
    sourceUrl: "https://checkatrade.com/",
    dateOfScraping: "2025-01-15"
  },
  {
    companyName: "Expert Roofing Solutions",
    tradespersonName: "Michael Brown",
    primaryIndustry: "Roofing Specialists",
    fullAddress: "78 Church Lane, London",
    postcode: "SW1A 3CC",
    websiteUrl: "https://expertroofing.co.uk",
    phoneNumber: "020 7345 6789",
    emailAddress: "mike@expertroofing.co.uk",
    sourceUrl: "https://mybuilder.com/",
    dateOfScraping: "2025-01-15"
  },
  {
    companyName: "Capital Groundworks",
    tradespersonName: "David Wilson",
    primaryIndustry: "Groundworkers",
    fullAddress: "156 High Street, London",
    postcode: "SW1A 4DD",
    websiteUrl: "",
    phoneNumber: "020 7456 7890",
    emailAddress: "david@capitalgroundworks.com",
    sourceUrl: "https://maps.google.com/",
    dateOfScraping: "2025-01-15"
  },
  {
    companyName: "Heritage Brickwork",
    tradespersonName: "Robert Taylor",
    primaryIndustry: "Bricklayers & Stonemasons",
    fullAddress: "89 Market Square, London",
    postcode: "SW1A 5EE",
    websiteUrl: "https://heritagebrickwork.co.uk",
    phoneNumber: "020 7567 8901",
    emailAddress: "robert@heritagebrickwork.co.uk",
    sourceUrl: "https://checkatrade.com/",
    dateOfScraping: "2025-01-15"
  },
  {
    companyName: "Elite Interior Design",
    tradespersonName: "Emma Davis",
    primaryIndustry: "Interior Designers",
    fullAddress: "234 Design Avenue, London",
    postcode: "SW1A 6FF",
    websiteUrl: "https://eliteinteriors.london",
    phoneNumber: "020 7678 9012",
    emailAddress: "emma@eliteinteriors.london",
    sourceUrl: "https://mybuilder.com/",
    dateOfScraping: "2025-01-15"
  },
  {
    companyName: "All-Fix Property Services",
    tradespersonName: "James Miller",
    primaryIndustry: "Property Maintenance",
    fullAddress: "67 Service Road, London",
    postcode: "SW1A 7GG",
    websiteUrl: "",
    phoneNumber: "020 7789 0123",
    emailAddress: "james@allfixservices.co.uk",
    sourceUrl: "https://maps.google.com/",
    dateOfScraping: "2025-01-15"
  },
  {
    companyName: "Perfect Plastering Co",
    tradespersonName: "Thomas Anderson",
    primaryIndustry: "Plasterers",
    fullAddress: "12 Craft Street, London",
    postcode: "SW1A 8HH",
    websiteUrl: "https://perfectplastering.london",
    phoneNumber: "020 7890 1234",
    emailAddress: "tom@perfectplastering.london",
    sourceUrl: "https://checkatrade.com/",
    dateOfScraping: "2025-01-15"
  },
  {
    companyName: "Green Thumb Landscaping",
    tradespersonName: "Lisa Garcia",
    primaryIndustry: "Landscapers",
    fullAddress: "345 Garden Way, London",
    postcode: "SW1A 9II",
    websiteUrl: "https://greenthumblandscaping.co.uk",
    phoneNumber: "020 7901 2345",
    emailAddress: "lisa@greenthumblandscaping.co.uk",
    sourceUrl: "https://mybuilder.com/",
    dateOfScraping: "2025-01-15"
  },
  {
    companyName: "Swift Electrical Services",
    tradespersonName: "Kevin White",
    primaryIndustry: "Electricians",
    fullAddress: "789 Power Street, London",
    postcode: "SW1A 0JJ",
    websiteUrl: "https://swiftelectrical.london",
    phoneNumber: "020 7012 3456",
    emailAddress: "kevin@swiftelectrical.london",
    sourceUrl: "https://maps.google.com/",
    dateOfScraping: "2025-01-15"
  },
  {
    companyName: "Pro Plumbing Solutions",
    tradespersonName: "Mark Thompson",
    primaryIndustry: "Plumbers",
    fullAddress: "456 Water Lane, London",
    postcode: "SW1A 1KK",
    websiteUrl: "",
    phoneNumber: "020 7123 4567",
    emailAddress: "mark@proplumbing.co.uk",
    sourceUrl: "https://checkatrade.com/",
    dateOfScraping: "2025-01-15"
  },
  {
    companyName: "Warm Home Heating",
    tradespersonName: "Peter Clark",
    primaryIndustry: "Heating Engineers",
    fullAddress: "321 Boiler Street, London",
    postcode: "SW1A 2LL",
    websiteUrl: "https://warmhomeheating.co.uk",
    phoneNumber: "020 7234 5678",
    emailAddress: "peter@warmhomeheating.co.uk",
    sourceUrl: "https://mybuilder.com/",
    dateOfScraping: "2025-01-15"
  }
];